<a href="https://colab.research.google.com/github/AmirHosseinAlikhahMishamandani/Code-in-the-Cloud-Python-Mastery-with-Google-Colab/blob/main/Code_in_the_Cloud_Python_Mastery_with_Google_Colab%E2%80%8A_%E2%80%8APart_6%E2%80%8A_%E2%80%8AModules.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Code in the Cloud: Python Mastery with Google Colab - Part 6 - Modules

## Custom Modules using Functions

In [1]:
import geometry

# Calculate the area and perimeter of a square
square_side = 5
square_area = geometry.square_area(square_side)
square_perimeter = geometry.square_perimeter(square_side)

print("Square Area:", square_area)
print("Square Perimeter:", square_perimeter)

# Calculate the area and perimeter of a rectangle
rectangle_length = 6
rectangle_width = 4
rectangle_area = geometry.rectangle_area(rectangle_length, rectangle_width)
rectangle_perimeter = geometry.rectangle_perimeter(rectangle_length, rectangle_width)

print("Rectangle Area:", rectangle_area)
print("Rectangle Perimeter:", rectangle_perimeter)

# Calculate the area and circumference of a circle
circle_radius = 3
circle_area = geometry.circle_area(circle_radius)
circle_circumference = geometry.circle_circumference(circle_radius)

print("Circle Area:", circle_area)
print("Circle Circumference:", circle_circumference)

Square Area: 25
Square Perimeter: 20
Rectangle Area: 24
Rectangle Perimeter: 20
Circle Area: 28.27433385
Circle Circumference: 18.849555900000002


In [2]:
import geometry as gm

# Calculate the area and perimeter of a square
square_side = 5
square_area = gm.square_area(square_side)
square_perimeter = gm.square_perimeter(square_side)

print("Square Area:", square_area)
print("Square Perimeter:", square_perimeter)

# Calculate the area and perimeter of a rectangle
rectangle_length = 6
rectangle_width = 4
rectangle_area = gm.rectangle_area(rectangle_length, rectangle_width)
rectangle_perimeter = gm.rectangle_perimeter(rectangle_length, rectangle_width)

print("Rectangle Area:", rectangle_area)
print("Rectangle Perimeter:", rectangle_perimeter)

# Calculate the area and circumference of a circle
circle_radius = 3
circle_area = gm.circle_area(circle_radius)
circle_circumference = gm.circle_circumference(circle_radius)

print("Circle Area:", circle_area)
print("Circle Circumference:", circle_circumference)

Square Area: 25
Square Perimeter: 20
Rectangle Area: 24
Rectangle Perimeter: 20
Circle Area: 28.27433385
Circle Circumference: 18.849555900000002


## Custom Modules using Classes

In [3]:
from bank_account import BankAccount

# Create two bank accounts
account1 = BankAccount("123456")
account2 = BankAccount("789012", 1000)

# Perform operations on the accounts
account1.deposit(500)
account2.withdraw(200)
account1.get_balance()
account2.get_balance()

Deposited 500 units. New balance: 500
Withdrew 200 units. New balance: 800
Account balance: 500
Account balance: 800


## Import Third-party Module

In [4]:
!pip install numpy

## Numpy

In [16]:
import numpy as np

In [15]:
# Basic arithmetic operations
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print("Addition:", a + b)
print("Subtraction:", a - b)
print("Multiplication:", a * b)
print("Division:", a / b)

Addition: [5 7 9]
Subtraction: [-3 -3 -3]
Multiplication: [ 4 10 18]
Division: [0.25 0.4  0.5 ]


In [7]:
# Creating arrays
arr1 = np.array([1, 2, 3])
print("arr1:", arr1)

arr2 = np.zeros((2, 3))  # 2x3 array of zeros
print("arr2:", arr2)

arr3 = np.ones((3, 2))    # 3x2 array of ones
print("arr3:", arr3)

arr4 = np.arange(0, 10, 2)  # Array with values from 0 to 9 with step 2
print("arr4:", arr4)

arr5 = np.linspace(0, 1, 5)  # Array with 5 evenly spaced values between 0 and 1
print("arr5:", arr5)

arr1: [1 2 3]
arr2: [[0. 0. 0.]
 [0. 0. 0.]]
arr3: [[1. 1.]
 [1. 1.]
 [1. 1.]]
arr4: [0 2 4 6 8]
arr5: [0.   0.25 0.5  0.75 1.  ]


In [8]:
# Array manipulation
arr = np.arange(9).reshape(3, 3)  # Reshape 1D array to 3x3
print("Original array:")
print(arr)

# Transpose array
arr_transposed = arr.T
print("\nTransposed array:")
print(arr_transposed)

Original array:
[[0 1 2]
 [3 4 5]
 [6 7 8]]

Transposed array:
[[0 3 6]
 [1 4 7]
 [2 5 8]]


In [9]:
# Mathematical functions
arr = np.array([1, 2, 3, 4])

print("Mean:", np.mean(arr))
print("Standard Deviation:", np.std(arr))
print("Sum:", np.sum(arr))
print("Maximum value:", np.max(arr))

Mean: 2.5
Standard Deviation: 1.118033988749895
Sum: 10
Maximum value: 4


In [10]:
# Indexing and slicing
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

print("Element at index (1, 2):", arr[1, 2])
print("First row:", arr[0])
print("First column:", arr[:, 0])
print("Slicing a subarray:")
print(arr[:2, 1:])

Element at index (1, 2): 6
First row: [1 2 3]
First column: [1 4 7]
Slicing a subarray:
[[2 3]
 [5 6]]


In [11]:
# Broadcasting
a = np.array([[1, 2, 3], [4, 5, 6]])
b = np.array([10, 20, 30])

print("Original arrays:")
print("a:", a)
print("b:", b)

print("\nBroadcasting result:")
print(a + b)

Original arrays:
a: [[1 2 3]
 [4 5 6]]
b: [10 20 30]

Broadcasting result:
[[11 22 33]
 [14 25 36]]


In [12]:
# Linear algebra
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

# Matrix multiplication
C = np.dot(A, B)
print("Matrix multiplication:")
print(C)

Matrix multiplication:
[[19 22]
 [43 50]]


In [13]:
# Random sampling
random_array = np.random.rand(3, 3)  # Random numbers between 0 and 1
print("Random array:")
print(random_array)

Random array:
[[0.82970076 0.9714654  0.9701973 ]
 [0.70488984 0.60038061 0.64792625]
 [0.98783886 0.96611163 0.0283544 ]]
